include(GNUInstallDirs)
#set(CMAKE_INSTALL_MESSAGE LAZY)
if (DEFINED ENV{NDEBUG})
    set(CMAKE_BUILD_TYPE Release)
else()
    set(CMAKE_BUILD_TYPE Debug)
endif()
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
enable_testing()
